### This file is downloaded from https://github.com/vimotest/mps-gradle-scripts/raw/main/.github/workflows/github-actions-integration.yaml

name: Integration Build

on:
  push:
    branches:
      - '*'

jobs:
  call-build-workflow:
    uses: ./.github/workflows/workflow-build.yaml
